/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlos
 */
public class jfrmClienteJavaConvT extends javax.swing.JFrame {

    /**
     * Creates new form jfrmClienteJavaConvT
     */
    public jfrmClienteJavaConvT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgGrados = new javax.swing.ButtonGroup();
        jlbGrados = new javax.swing.JLabel();
        jtfGrados = new javax.swing.JTextField();
        jbtConvertir = new javax.swing.JButton();
        jrbCentAFahr = new javax.swing.JRadioButton();
        jrbFahrACent = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversion Centigrados <--> Fahrenheit");
        setResizable(false);

        jlbGrados.setText("Grados");

        jtfGrados.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfGrados.setText("0.00");
        jtfGrados.setToolTipText("Ingrese un Numero");
        jtfGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfGradosActionPerformed(evt);
            }
        });

        jbtConvertir.setText("Convertir");
        jbtConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConvertirActionPerformed(evt);
            }
        });

        jbgGrados.add(jrbCentAFahr);
        jrbCentAFahr.setSelected(true);
        jrbCentAFahr.setText("Centigrados a Fahrenheit");
        jrbCentAFahr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCentAFahrActionPerformed(evt);
            }
        });

        jbgGrados.add(jrbFahrACent);
        jrbFahrACent.setText("Fahrenheit a Centigrados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jrbFahrACent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbCentAFahr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfGrados)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jlbGrados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtConvertir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbCentAFahr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbFahrACent)
                .addGap(28, 28, 28))
        );

        jlbGrados.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfGradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfGradosActionPerformed

    private void jbtConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConvertirActionPerformed
        // TODO add your handling code here:
        double nGrados = 0.0;
        try{
            //obtener el valor escrito en la caja de texto
            nGrados = Double.parseDouble(jtfGrados.getText());
            //Realizar la conversion invocando al metodo correspondiente del servicio
            if(jrbCentAFahr.isSelected()){
                nGrados= convCentAFahr(nGrados);
            }
            if(jrbFahrACent.isSelected()){
                nGrados= convFahrACent(nGrados);
            }
            //Mostrar el Resultado en la caja de texto
            jtfGrados.setText(Double.toString(nGrados));
            
        }catch(NumberFormatException ex){
        javax.swing.JOptionPane.showMessageDialog(null, hello(jtfGrados.getText()));
    }catch(Exception ex){
        javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
    }
    }//GEN-LAST:event_jbtConvertirActionPerformed

    private void jrbCentAFahrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCentAFahrActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrbCentAFahrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmClienteJavaConvT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmClienteJavaConvT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmClienteJavaConvT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmClienteJavaConvT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmClienteJavaConvT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jbgGrados;
    private javax.swing.JButton jbtConvertir;
    private javax.swing.JLabel jlbGrados;
    private javax.swing.JRadioButton jrbCentAFahr;
    private javax.swing.JRadioButton jrbFahrACent;
    private javax.swing.JTextField jtfGrados;
    // End of variables declaration//GEN-END:variables

    private static double convCentAFahr(double gCent) {
        jaxws.SWConverTemps_Service service = new jaxws.SWConverTemps_Service();
        jaxws.SWConverTemps port = service.getSWConverTempsPort();
        return port.convCentAFahr(gCent);
    }

    private static double convFahrACent(double gFahr) {
        jaxws.SWConverTemps_Service service = new jaxws.SWConverTemps_Service();
        jaxws.SWConverTemps port = service.getSWConverTempsPort();
        return port.convFahrACent(gFahr);
    }

    private static String hello(java.lang.String name) {
        jaxws.SWConverTemps_Service service = new jaxws.SWConverTemps_Service();
        jaxws.SWConverTemps port = service.getSWConverTempsPort();
        return port.hello(name);
    }
    
    
}
